apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::166189617576:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1V7JX77QYR8D4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::166189617576:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-15T10:05:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1926"
  uid: 863fe0de-7383-43ce-b3c0-2e38bd1e2ee2
